# Generated by Django 5.2.6 on 2025-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
            ],
            options={
                'permissions': [('can_add_book', 'Can add a new book'), ('can_edit_book', 'Can edit a book'), ('can_delete_book', 'Can delete a book')],
            },
        ),
    ]
